{% set name = "meeko" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meeko-{{ version }}.tar.gz
  sha256: fbe8908640cd17dabc4c8b0e6958f479907ae532e658ea673f181600a59ea7bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.12
    - numpy
    - scipy
    - rdkit
    - gemmi
    - prody

test:
  requires:
    - python {{ python_min }}
  imports:
    - meeko
  commands:
    - mk_export.py --help
    - mk_prepare_ligand.py --help
    - mk_prepare_receptor.py --help

about:
  home: https://github.com/ccsb-scripps/meeko
  summary: Python package for preparing small molecule for docking
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nbruciaferri
    - diogomart
